// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v7.34.1
// source: pkg/dbus/pb/flydigi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionType int32

const (
	ConnectionType_UNKNOWN  ConnectionType = 0
	ConnectionType_WIRELESS ConnectionType = 1
	ConnectionType_WIRED    ConnectionType = 2
)

// Enum value maps for ConnectionType.
var (
	ConnectionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "WIRELESS",
		2: "WIRED",
	}
	ConnectionType_value = map[string]int32{
		"UNKNOWN":  0,
		"WIRELESS": 1,
		"WIRED":    2,
	}
)

func (x ConnectionType) Enum() *ConnectionType {
	p := new(ConnectionType)
	*p = x
	return p
}

func (x ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_dbus_pb_flydigi_proto_enumTypes[0].Descriptor()
}

func (ConnectionType) Type() protoreflect.EnumType {
	return &file_pkg_dbus_pb_flydigi_proto_enumTypes[0]
}

func (x ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionType.Descriptor instead.
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{0}
}

type GamepadInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId       int32          `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	BatteryPercent int32          `protobuf:"varint,2,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	ConnectionType ConnectionType `protobuf:"varint,3,opt,name=connection_type,json=connectionType,proto3,enum=flydigi.ConnectionType" json:"connection_type,omitempty"`
	CpuType        string         `protobuf:"bytes,4,opt,name=cpu_type,json=cpuType,proto3" json:"cpu_type,omitempty"`
	CpuName        string         `protobuf:"bytes,5,opt,name=cpu_name,json=cpuName,proto3" json:"cpu_name,omitempty"`
	ProtocolMode   string         `protobuf:"bytes,6,opt,name=protocol_mode,json=protocolMode,proto3" json:"protocol_mode,omitempty"`
}

func (x *GamepadInfo) Reset() {
	*x = GamepadInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamepadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamepadInfo) ProtoMessage() {}

func (x *GamepadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamepadInfo.ProtoReflect.Descriptor instead.
func (*GamepadInfo) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{0}
}

func (x *GamepadInfo) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GamepadInfo) GetBatteryPercent() int32 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *GamepadInfo) GetConnectionType() ConnectionType {
	if x != nil {
		return x.ConnectionType
	}
	return ConnectionType_UNKNOWN
}

func (x *GamepadInfo) GetCpuType() string {
	if x != nil {
		return x.CpuType
	}
	return ""
}

func (x *GamepadInfo) GetCpuName() string {
	if x != nil {
		return x.CpuName
	}
	return ""
}

func (x *GamepadInfo) GetProtocolMode() string {
	if x != nil {
		return x.ProtocolMode
	}
	return ""
}

type GamepadConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftJoystick   *JoystickConfiguration `protobuf:"bytes,1,opt,name=left_joystick,json=leftJoystick,proto3" json:"left_joystick,omitempty"`
	RightJoystick  *JoystickConfiguration `protobuf:"bytes,2,opt,name=right_joystick,json=rightJoystick,proto3" json:"right_joystick,omitempty"`
	ButtonMappings []*ButtonMapping       `protobuf:"bytes,3,rep,name=button_mappings,json=buttonMappings,proto3" json:"button_mappings,omitempty"`
}

func (x *GamepadConfiguration) Reset() {
	*x = GamepadConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamepadConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamepadConfiguration) ProtoMessage() {}

func (x *GamepadConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamepadConfiguration.ProtoReflect.Descriptor instead.
func (*GamepadConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{1}
}

func (x *GamepadConfiguration) GetLeftJoystick() *JoystickConfiguration {
	if x != nil {
		return x.LeftJoystick
	}
	return nil
}

func (x *GamepadConfiguration) GetRightJoystick() *JoystickConfiguration {
	if x != nil {
		return x.RightJoystick
	}
	return nil
}

func (x *GamepadConfiguration) GetButtonMappings() []*ButtonMapping {
	if x != nil {
		return x.ButtonMappings
	}
	return nil
}

type JoystickConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deadzone int32 `protobuf:"varint,1,opt,name=deadzone,proto3" json:"deadzone,omitempty"`
}

func (x *JoystickConfiguration) Reset() {
	*x = JoystickConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoystickConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoystickConfiguration) ProtoMessage() {}

func (x *JoystickConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoystickConfiguration.ProtoReflect.Descriptor instead.
func (*JoystickConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{2}
}

func (x *JoystickConfiguration) GetDeadzone() int32 {
	if x != nil {
		return x.Deadzone
	}
	return 0
}

type ButtonMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId       int32  `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	MappedKeyId int32  `protobuf:"varint,3,opt,name=mapped_key_id,json=mappedKeyId,proto3" json:"mapped_key_id,omitempty"`
	MappedKey   string `protobuf:"bytes,4,opt,name=mapped_key,json=mappedKey,proto3" json:"mapped_key,omitempty"`
	IsOwn       bool   `protobuf:"varint,5,opt,name=is_own,json=isOwn,proto3" json:"is_own,omitempty"`
	IsMapped    bool   `protobuf:"varint,6,opt,name=is_mapped,json=isMapped,proto3" json:"is_mapped,omitempty"`
}

func (x *ButtonMapping) Reset() {
	*x = ButtonMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ButtonMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonMapping) ProtoMessage() {}

func (x *ButtonMapping) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonMapping.ProtoReflect.Descriptor instead.
func (*ButtonMapping) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{3}
}

func (x *ButtonMapping) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *ButtonMapping) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ButtonMapping) GetMappedKeyId() int32 {
	if x != nil {
		return x.MappedKeyId
	}
	return 0
}

func (x *ButtonMapping) GetMappedKey() string {
	if x != nil {
		return x.MappedKey
	}
	return ""
}

func (x *ButtonMapping) GetIsOwn() bool {
	if x != nil {
		return x.IsOwn
	}
	return false
}

func (x *ButtonMapping) GetIsMapped() bool {
	if x != nil {
		return x.IsMapped
	}
	return false
}

type LedsOff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LedsOff) Reset() {
	*x = LedsOff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedsOff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsOff) ProtoMessage() {}

func (x *LedsOff) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsOff.ProtoReflect.Descriptor instead.
func (*LedsOff) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{4}
}

type LedsSteady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color *Color `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *LedsSteady) Reset() {
	*x = LedsSteady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedsSteady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsSteady) ProtoMessage() {}

func (x *LedsSteady) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsSteady.ProtoReflect.Descriptor instead.
func (*LedsSteady) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{5}
}

func (x *LedsSteady) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type LedsStreamlined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed float32 `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *LedsStreamlined) Reset() {
	*x = LedsStreamlined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedsStreamlined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsStreamlined) ProtoMessage() {}

func (x *LedsStreamlined) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsStreamlined.ProtoReflect.Descriptor instead.
func (*LedsStreamlined) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{6}
}

func (x *LedsStreamlined) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type LedsBreathing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color *Color  `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Speed float32 `protobuf:"fixed32,2,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *LedsBreathing) Reset() {
	*x = LedsBreathing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedsBreathing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsBreathing) ProtoMessage() {}

func (x *LedsBreathing) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsBreathing.ProtoReflect.Descriptor instead.
func (*LedsBreathing) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{7}
}

func (x *LedsBreathing) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *LedsBreathing) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type LedsGradient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartColor *Color  `protobuf:"bytes,1,opt,name=start_color,json=startColor,proto3" json:"start_color,omitempty"`
	EndColor   *Color  `protobuf:"bytes,2,opt,name=end_color,json=endColor,proto3" json:"end_color,omitempty"`
	Speed      float32 `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *LedsGradient) Reset() {
	*x = LedsGradient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedsGradient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsGradient) ProtoMessage() {}

func (x *LedsGradient) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsGradient.ProtoReflect.Descriptor instead.
func (*LedsGradient) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{8}
}

func (x *LedsGradient) GetStartColor() *Color {
	if x != nil {
		return x.StartColor
	}
	return nil
}

func (x *LedsGradient) GetEndColor() *Color {
	if x != nil {
		return x.EndColor
	}
	return nil
}

func (x *LedsGradient) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type LedsFeedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed float32 `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *LedsFeedback) Reset() {
	*x = LedsFeedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedsFeedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsFeedback) ProtoMessage() {}

func (x *LedsFeedback) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsFeedback.ProtoReflect.Descriptor instead.
func (*LedsFeedback) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{9}
}

func (x *LedsFeedback) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type LedsConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brightness float32 `protobuf:"fixed32,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
	// Types that are assignable to Leds:
	//
	//	*LedsConfiguration_Off
	//	*LedsConfiguration_Steady
	//	*LedsConfiguration_Streamlined
	//	*LedsConfiguration_Gradient
	//	*LedsConfiguration_Breathing
	//	*LedsConfiguration_Feedback
	Leds isLedsConfiguration_Leds `protobuf_oneof:"leds"`
}

func (x *LedsConfiguration) Reset() {
	*x = LedsConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsConfiguration) ProtoMessage() {}

func (x *LedsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsConfiguration.ProtoReflect.Descriptor instead.
func (*LedsConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{10}
}

func (x *LedsConfiguration) GetBrightness() float32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (m *LedsConfiguration) GetLeds() isLedsConfiguration_Leds {
	if m != nil {
		return m.Leds
	}
	return nil
}

func (x *LedsConfiguration) GetOff() *LedsOff {
	if x, ok := x.GetLeds().(*LedsConfiguration_Off); ok {
		return x.Off
	}
	return nil
}

func (x *LedsConfiguration) GetSteady() *LedsSteady {
	if x, ok := x.GetLeds().(*LedsConfiguration_Steady); ok {
		return x.Steady
	}
	return nil
}

func (x *LedsConfiguration) GetStreamlined() *LedsStreamlined {
	if x, ok := x.GetLeds().(*LedsConfiguration_Streamlined); ok {
		return x.Streamlined
	}
	return nil
}

func (x *LedsConfiguration) GetGradient() *LedsGradient {
	if x, ok := x.GetLeds().(*LedsConfiguration_Gradient); ok {
		return x.Gradient
	}
	return nil
}

func (x *LedsConfiguration) GetBreathing() *LedsBreathing {
	if x, ok := x.GetLeds().(*LedsConfiguration_Breathing); ok {
		return x.Breathing
	}
	return nil
}

func (x *LedsConfiguration) GetFeedback() *LedsFeedback {
	if x, ok := x.GetLeds().(*LedsConfiguration_Feedback); ok {
		return x.Feedback
	}
	return nil
}

type isLedsConfiguration_Leds interface {
	isLedsConfiguration_Leds()
}

type LedsConfiguration_Off struct {
	Off *LedsOff `protobuf:"bytes,10,opt,name=off,proto3,oneof"`
}

type LedsConfiguration_Steady struct {
	Steady *LedsSteady `protobuf:"bytes,12,opt,name=steady,proto3,oneof"`
}

type LedsConfiguration_Streamlined struct {
	Streamlined *LedsStreamlined `protobuf:"bytes,13,opt,name=streamlined,proto3,oneof"`
}

type LedsConfiguration_Gradient struct {
	Gradient *LedsGradient `protobuf:"bytes,14,opt,name=gradient,proto3,oneof"`
}

type LedsConfiguration_Breathing struct {
	Breathing *LedsBreathing `protobuf:"bytes,15,opt,name=breathing,proto3,oneof"`
}

type LedsConfiguration_Feedback struct {
	Feedback *LedsFeedback `protobuf:"bytes,16,opt,name=feedback,proto3,oneof"`
}

func (*LedsConfiguration_Off) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Steady) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Streamlined) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Gradient) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Breathing) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Feedback) isLedsConfiguration_Leds() {}

type Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rgb int32 `protobuf:"varint,1,opt,name=rgb,proto3" json:"rgb,omitempty"`
}

func (x *Color) Reset() {
	*x = Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dbus_pb_flydigi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_pkg_dbus_pb_flydigi_proto_rawDescGZIP(), []int{11}
}

func (x *Color) GetRgb() int32 {
	if x != nil {
		return x.Rgb
	}
	return 0
}

var File_pkg_dbus_pb_flydigi_proto protoreflect.FileDescriptor

var file_pkg_dbus_pb_flydigi_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x62, 0x75, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x6c,
	0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x6c, 0x79,
	0x64, 0x69, 0x67, 0x69, 0x22, 0xf0, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x70, 0x61, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x62, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x79, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x63, 0x70, 0x75, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x70, 0x75, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x70, 0x75, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0xe3, 0x01, 0x0a, 0x14, 0x47, 0x61, 0x6d, 0x65,
	0x70, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x43, 0x0a, 0x0d, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x6a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67,
	0x69, 0x2e, 0x4a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6c, 0x65, 0x66, 0x74, 0x4a, 0x6f, 0x79,
	0x73, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x45, 0x0a, 0x0e, 0x72, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x6a,
	0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x4a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x4a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x3f, 0x0a, 0x0f,
	0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e,
	0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x0e, 0x62,
	0x75, 0x74, 0x74, 0x6f, 0x6e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x33, 0x0a,
	0x15, 0x4a, 0x6f, 0x79, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x7a, 0x6f,
	0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x7a, 0x6f,
	0x6e, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x0d, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x4d, 0x61, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a,
	0x0d, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x64, 0x4b, 0x65, 0x79,
	0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x6f, 0x77, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x69, 0x73, 0x4f, 0x77, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6d, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4d, 0x61,
	0x70, 0x70, 0x65, 0x64, 0x22, 0x09, 0x0a, 0x07, 0x4c, 0x65, 0x64, 0x73, 0x4f, 0x66, 0x66, 0x22,
	0x32, 0x0a, 0x0a, 0x4c, 0x65, 0x64, 0x73, 0x53, 0x74, 0x65, 0x61, 0x64, 0x79, 0x12, 0x24, 0x0a,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66,
	0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x22, 0x27, 0x0a, 0x0f, 0x4c, 0x65, 0x64, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x4b, 0x0a, 0x0d,
	0x4c, 0x65, 0x64, 0x73, 0x42, 0x72, 0x65, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66,
	0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x4c, 0x65,
	0x64, 0x73, 0x47, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x09, 0x65,
	0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x08,
	0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x24,
	0x0a, 0x0c, 0x4c, 0x65, 0x64, 0x73, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73,
	0x70, 0x65, 0x65, 0x64, 0x22, 0xf0, 0x02, 0x0a, 0x11, 0x4c, 0x65, 0x64, 0x73, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x24, 0x0a, 0x03, 0x6f, 0x66,
	0x66, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67,
	0x69, 0x2e, 0x4c, 0x65, 0x64, 0x73, 0x4f, 0x66, 0x66, 0x48, 0x00, 0x52, 0x03, 0x6f, 0x66, 0x66,
	0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x65, 0x61, 0x64, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x4c, 0x65, 0x64, 0x73, 0x53,
	0x74, 0x65, 0x61, 0x64, 0x79, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x65, 0x61, 0x64, 0x79, 0x12,
	0x3c, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x4c,
	0x65, 0x64, 0x73, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x48, 0x00,
	0x52, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x33, 0x0a,
	0x08, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x4c, 0x65, 0x64, 0x73, 0x47, 0x72,
	0x61, 0x64, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x08, 0x67, 0x72, 0x61, 0x64, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x36, 0x0a, 0x09, 0x62, 0x72, 0x65, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e,
	0x4c, 0x65, 0x64, 0x73, 0x42, 0x72, 0x65, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x09, 0x62, 0x72, 0x65, 0x61, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x33, 0x0a, 0x08, 0x66, 0x65,
	0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66,
	0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x2e, 0x4c, 0x65, 0x64, 0x73, 0x46, 0x65, 0x65, 0x64, 0x62,
	0x61, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x42,
	0x06, 0x0a, 0x04, 0x6c, 0x65, 0x64, 0x73, 0x22, 0x19, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x67, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x67, 0x62, 0x2a, 0x36, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x57, 0x49, 0x52, 0x45, 0x4c, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x57, 0x49, 0x52, 0x45, 0x44, 0x10, 0x02, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x30, 0x31, 0x2f,
	0x66, 0x6c, 0x79, 0x64, 0x69, 0x67, 0x69, 0x63, 0x74, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64,
	0x62, 0x75, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_dbus_pb_flydigi_proto_rawDescOnce sync.Once
	file_pkg_dbus_pb_flydigi_proto_rawDescData = file_pkg_dbus_pb_flydigi_proto_rawDesc
)

func file_pkg_dbus_pb_flydigi_proto_rawDescGZIP() []byte {
	file_pkg_dbus_pb_flydigi_proto_rawDescOnce.Do(func() {
		file_pkg_dbus_pb_flydigi_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_dbus_pb_flydigi_proto_rawDescData)
	})
	return file_pkg_dbus_pb_flydigi_proto_rawDescData
}

var file_pkg_dbus_pb_flydigi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_dbus_pb_flydigi_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_dbus_pb_flydigi_proto_goTypes = []interface{}{
	(ConnectionType)(0),           // 0: flydigi.ConnectionType
	(*GamepadInfo)(nil),           // 1: flydigi.GamepadInfo
	(*GamepadConfiguration)(nil),  // 2: flydigi.GamepadConfiguration
	(*JoystickConfiguration)(nil), // 3: flydigi.JoystickConfiguration
	(*ButtonMapping)(nil),         // 4: flydigi.ButtonMapping
	(*LedsOff)(nil),               // 5: flydigi.LedsOff
	(*LedsSteady)(nil),            // 6: flydigi.LedsSteady
	(*LedsStreamlined)(nil),       // 7: flydigi.LedsStreamlined
	(*LedsBreathing)(nil),         // 8: flydigi.LedsBreathing
	(*LedsGradient)(nil),          // 9: flydigi.LedsGradient
	(*LedsFeedback)(nil),          // 10: flydigi.LedsFeedback
	(*LedsConfiguration)(nil),     // 11: flydigi.LedsConfiguration
	(*Color)(nil),                 // 12: flydigi.Color
}
var file_pkg_dbus_pb_flydigi_proto_depIdxs = []int32{
	0,  // 0: flydigi.GamepadInfo.connection_type:type_name -> flydigi.ConnectionType
	3,  // 1: flydigi.GamepadConfiguration.left_joystick:type_name -> flydigi.JoystickConfiguration
	3,  // 2: flydigi.GamepadConfiguration.right_joystick:type_name -> flydigi.JoystickConfiguration
	4,  // 3: flydigi.GamepadConfiguration.button_mappings:type_name -> flydigi.ButtonMapping
	12, // 4: flydigi.LedsSteady.color:type_name -> flydigi.Color
	12, // 5: flydigi.LedsBreathing.color:type_name -> flydigi.Color
	12, // 6: flydigi.LedsGradient.start_color:type_name -> flydigi.Color
	12, // 7: flydigi.LedsGradient.end_color:type_name -> flydigi.Color
	5,  // 8: flydigi.LedsConfiguration.off:type_name -> flydigi.LedsOff
	6,  // 9: flydigi.LedsConfiguration.steady:type_name -> flydigi.LedsSteady
	7,  // 10: flydigi.LedsConfiguration.streamlined:type_name -> flydigi.LedsStreamlined
	9,  // 11: flydigi.LedsConfiguration.gradient:type_name -> flydigi.LedsGradient
	8,  // 12: flydigi.LedsConfiguration.breathing:type_name -> flydigi.LedsBreathing
	10, // 13: flydigi.LedsConfiguration.feedback:type_name -> flydigi.LedsFeedback
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pkg_dbus_pb_flydigi_proto_init() }
func file_pkg_dbus_pb_flydigi_proto_init() {
	if File_pkg_dbus_pb_flydigi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_dbus_pb_flydigi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamepadInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamepadConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoystickConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ButtonMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedsOff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedsSteady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedsStreamlined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedsBreathing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedsGradient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedsFeedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedsConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_dbus_pb_flydigi_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_dbus_pb_flydigi_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*LedsConfiguration_Off)(nil),
		(*LedsConfiguration_Steady)(nil),
		(*LedsConfiguration_Streamlined)(nil),
		(*LedsConfiguration_Gradient)(nil),
		(*LedsConfiguration_Breathing)(nil),
		(*LedsConfiguration_Feedback)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_dbus_pb_flydigi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_dbus_pb_flydigi_proto_goTypes,
		DependencyIndexes: file_pkg_dbus_pb_flydigi_proto_depIdxs,
		EnumInfos:         file_pkg_dbus_pb_flydigi_proto_enumTypes,
		MessageInfos:      file_pkg_dbus_pb_flydigi_proto_msgTypes,
	}.Build()
	File_pkg_dbus_pb_flydigi_proto = out.File
	file_pkg_dbus_pb_flydigi_proto_rawDesc = nil
	file_pkg_dbus_pb_flydigi_proto_goTypes = nil
	file_pkg_dbus_pb_flydigi_proto_depIdxs = nil
}
